#!/bin/sh

#
# Copyright © 2015, 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, please define the SHELL environment variable to point to it.
#
#   Important for patching:
#
#   (2) This script is generated from the template in
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       If you wish to make modifications, please modify the template and
#       generate a new script from it rather than editing this file.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25031)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && [ "$MAX_FD" = "maximum" ] ; then
    # We can only hope that limit is circular.
    ulimit -H -n > /dev/null \
        && ulimit -S -n "$( ulimit -H -n )" > /dev/null \
        || warn "Could not set maximum file descriptor limit: current maximum is $( ulimit -n )"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `eval lastarg=\$$#` and `eval \$$i=\$lastarg` approach would
        # work, but that's harder to read and potentially vulnerable to eval-ing
        # values that might be specially crafted to cause trouble.
        #
        # NB: AFAIK, there is no way to push so save the $# for later restore
        eval "nargs=\$#"
        while [ $# -gt 0 ] ; do
            eval "argn=\$${1}"
            shift
            set -- "$@" "$argn"
        done
        eval "set -- \$@ \"\$nargs\""
    done
fi

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment
#     variable that might be set on a different machine than where it is used.

# Use "x" prefix to avoid clash with array element starting with '-'
# shellcheck disable=SC2294
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "x" is returned
while [ "$#" -gt 0 ] ; do
    # Perform primitive deparsing of the argument, to attempt to preserve
    # the original intent of the caller, while avoiding potential problems
    # if the argument contains shell metacharacters.
    # The basic algorithm is:
    #   * If the argument contains no problematic characters, leave it as is
    #   * Otherwise, if the argument contains no single quotes, wrap it in double quotes
    #   * Otherwise, if the argument contains no double quotes, wrap it in single quotes
    #   * Otherwise, use single quotes and escape any single quotes that appear in the argument
    #   * Concatenate the resulting string to the command
    arg="$1"
    shift
    if [ -z "$arg" ] ; then
        set -- "$@" ""
    elif printf "%s\n" "$arg" | grep -Eq '[@#\$`"\!\\<>{}\*\[\]\?;[:space:]()]' ; then
        if printf "%s\n" "$arg" | grep -q "'" ; then
            if printf "%s\n" "$arg" | grep -q '"' ; then
                # Both single and double quotes in the argument - escape single quotes
                arg=$( printf "%s\n" "$arg" | sed "s/'/'\\\\''/g" )
                set -- "$@" "'$arg'"
            else
                set -- "$@" "'$arg'"
            fi
        else
            set -- "$@" "\"$arg\""
        fi
    else
        set -- "$@" "$arg"
    fi
done

exec "$JAVACMD" \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"